package:
  name: imagepicker
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.1') }}

source:
  git_url: ../

build:
  entry_points:
    - imagepicker = imagepicker.main:main
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.6
    - ruamel.yaml >=0.15
    - pyqt >=5.6

test:
  imports:
    - imagepicker
  commands:
    - imagepicker -V

about:
  home: https://github.com/necaris/imagepicker
